on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Build Unikorn Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./src"
          binary_name: "unikorn"
          goversion: "https://dl.google.com/go/go1.16.5.linux-amd64.tar.gz"
